<a href="https://colab.research.google.com/github/luisfranc123/Tutorials_Statistics_Numerical_Analysis/blob/main/Numerical_Methods/Chapter4_BranchingStatements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**4. Branching Statements**
---

**Textbook**: Phyton Programming and Numerical Methods

##**If-Else Statements**

Write a function `my_thermo_stat(temp, desired_temp)`. The return value of the function should be the string `"Heat"` if temp is less than `desired_temp` minus 5 degrees, `"AC"` if temp is ore than the `desired_temp` plus 5, and `"off"` otherwise.

In [ ]:
def my_thermo_stat(temp, desired_temp):
  """
  Changes the status of the thermostat based on
  temperature and desired temperature
  author
  date
  :type temp: Int
  :type desiredTemp: Int
  :rtype: String
  """

  if temp < desired_temp - 5:
    status = "Heat"
  elif temp > desired_temp + 5:
    status = "AC"
  else:
    status = "off"

  return status

In [ ]:
my_thermo_stat(65, 63)

'off'

A statement is called **nested** if it is entirely contained within another statement of the same type as itself. For example, a **nested if-statement** is an if-statement that is entirely contained within a clause of another if-statement.

**Example**: Think about what will appen whe the following code is executed. What are all the possible outcomes based on the input values of `x` and `y`?

In [ ]:
def my_nested_branching(x, y):
  """
  Nested Branching Statement Example
  author
  date
  :type x: Int
  :type y: Int
  :rtype: Int
  """

  if x > 2:
    if y < 2:
      out = x + y
    else:
      out = x - y
  else:
    if y > 2:
      out = x*y
    else:
      out = 0
  return out

In [ ]:
my_nested_branching(2, 2)

0

There are many logical functions that are designed to help you build branching statements. For example,
you can ask if a variable has a certain data type with function `isinstance`. There are also functions
that can tell you information about arrays of logicals like `any`, which computes to true if any element
in an array is true, and false otherwise, and `all`, which computes to true only if all the elements in an
array are true.
Sometimes you want to design your function to check the inputs of a function to ensure that your
function will be used properly. For example, the function `my_adder` in the previous chapter expects
doubles as input. If the user inputs a `list` or a `string` as one of the input variables, then the function
will throw an error or have unexpected results. To prevent this, you can put a check to tell the user
the function has not been used properly. This and other techniques for controlling errors are explored
further in Chapter 10. For the moment, you only need to know that we can use the raise statement
with a `TypeError` exception to stop a function's execution and throw an error with a specific text.

**EXAMPLE**: Modify `my_adder` to throw out a warning if the user does not input numerical values.
Try your function for nonnumerical inputs to show that the check works. When a statement is too
long, we can use the “\” symbol to break a line into multiple lines.

In [ ]:
def my_adder(a, b, c):
  """
  Calculate the sum of three numbers
  author
  date
  """

  # Check for erroneous input
  if not (isinstance(a, (int, float)) \
        or isinstance(b, (int, float)) \
        or isinstance(c, (int, float))):
          raise TypeError("Inputs must be numbers.")
  #Return output
  return a + b + c

In [ ]:
x = my_adder(1, 2, 3)
print(x)

6


In [ ]:
#x = my_adder("1", "2", "3")
#print(x)

Write a function called `is_odd` that returns `"odd"` if the input is an odd number and `"even"` if it is even. You can assume that input will be a positive integer.

In [ ]:
def is_odd(number):
  """
  function returns "odd" if the input is odd.
  "even" otherwise
  author
  date
  :type number: Int
  :rtype: String
  """

  # use modulo to check if the input divisible by 2
  if number % 2 == 0:
    # if divisible by 2, then input is not odd
    return "even"
  else:
    return "odd"

In [ ]:
is_odd(2)

'even'

In [ ]:
is_odd(3)

'odd'

Write a function called `my_circ_calc` that takes a numerical number, `r`, and a string `calc`, as input arguments. You may assume that `r` is positive, and that `calc` is either the string "area" or "circumference". The function `my_circ_calc` should compute the area of a circle with radius, `r`, if the string `calc` is the "area" and the circumference of a circle with radius, `r`, if `calc` is the "circumference".

In [ ]:
import numpy as np
def my_circ_calc(r, calc):
  """
  Calculate various circle measurements
  author
  date
  :type r: Int or Float
  :type calc: String
  :rtype: Int or Float
  """
  if calc == "area":
    return np.pi*r**2
  elif calc == "circumference":
    return 2*np.pi*r

In [ ]:
print(my_circ_calc(2.5, "area"))
print(my_circ_calc(2.5, "circumference"))

19.634954084936208
15.707963267948966


In [ ]:
print(my_circ_calc(np.array([2, 3, 4]), "circumference"))

[12.56637061 18.84955592 25.13274123]


##**Ternary Operators**

To implement the terniary operator in Python, use the construction presented below:

####**CONSTRUCTION**: ternary operator

`expression_if_true is condition else expression_if_false`

In [ ]:
# Example: Ternary operator

is_student = True
person = "student" if is_student else "not student"
print(person)

student


The above code is equivalent to the following block of codes:

In [ ]:
is_student = True
if is_student:
  person = "student"
else:
  person = "not student"
print(person)

student


**Ternary operators provide a simple way for branching and can make our codes concise**.

###**Problems**
---

1. Write a function `my_tip_calc(bill, party)` where `bill` is the total cost of a meal and `party` is
the number of people in the group. The tip should be calculated as 15% for a party strictly less than
six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party
11 or more. A couple of test cases are given below.

In [ ]:
def my_tip_calc(bill, party):
  """
  Author
  Date
  Function to calculate the tips given
  the number of people on a party
  :type bill: float
  :type party: int
  """
  if party < 6:
    tips = 0.15*bill
  elif party < 8:
    tips = 0.18*bill
  elif party < 11:
    tips = 0.20*bill
  else:
    tips = 0.2*bill

  return tips

In [ ]:
# Test 1
t = my_tip_calc(109.29, 3)
print(t)

16.3935


In [ ]:
# Test 2
t = my_tip_calc(109.29, 7)
print(t)

19.6722


In [ ]:
# Test 3
t = my_tip_calc(109.29, 12)
print(t)

21.858000000000004


2. Write a function `my_mult_operation(a, b, operation)`. The input argument, `operation`, is a string that is either `"plus"`, `"minus"`, `"mult"`, `"div"`,or"pow", and the function should compute: *a + b*, *a - b*, *a * b*,  *a/b*, and a for the respective values for `operation`. A couple of test cases are given below.



In [ ]:
def my_mult_operation(a, b, operation):
  """
  Author
  Date
  Function that evaluates the operation
  between two numbers accordingly
  :type a = float
  :type b = float
  :type operation = string
  """
  if operation == "plus":
    out = a + b
  elif operation == "minus":
    out = a - b
  elif operation == "mult":
    out = a*b
  elif operation == "div":
    out = a/b
  else:
    out = a**b
  return out

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])

my_mult_operation(x, y, "plus")

array([3, 5, 7, 9])

In [ ]:
print(my_mult_operation(x, y, "minus"))
print(my_mult_operation(x, y, "mult"))
print(my_mult_operation(x, y, "div"))
print(my_mult_operation(x, y, "pow"))

[-1 -1 -1 -1]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]
[   1    8   81 1024]


3. Most engineering systems have a built-in redundancy. That is, an engineering system has fail-safes
incorporated into the design to accomplish its purpose. Consider a nuclear reactor whose temperature
is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. Write a function `my_nuke_alarm(s1,s2,s3)` where `s1`, `s2`, and `s3` are the temperature readings for sensor 1, sensor 2, and sensor 3, respectively. The output should be the string `"alarm!"` if any two of the temperature readings disagree by strictly more than 10 degrees and `"normal"` otherwise

In [ ]:
def my_nuke_alarm(s1, s2, s3):
  """
  Function that sets an alarm if a
  pair of sensors are different from
  each other to an extent of 10 degrees.
  """

  def alarm(s1, s2):
    """
    Nested function that evaluates the condition
    """
    is_greater = 10
    message = "alarm!" if (s1 - s2) > is_greater else "normal"

    return message
  #Evaluate the condition between each pair of sensors

  alarm_1 = alarm(s1, s2)
  alarm_2 = alarm(s1,  s3)
  alarm_3 = alarm(s2, s3)
  set_alarms = [alarm_1, alarm_2, alarm_3]

  if len(list(set(set_alarms))) > 1:
    a = print("alarm!")
  else:
    a = print("normal")

  return a


In [ ]:
help(my_nuke_alarm)

Help on function my_nuke_alarm in module __main__:

my_nuke_alarm(s1, s2, s3)
    Function that sets an alarm if a 
    pair of sensors are different from 
    each other to an extent of 10 degrees.



In [ ]:
my_nuke_alarm(94, 96, 90)

normal


In [ ]:
my_nuke_alarm(94, 96, 80)

alarm!


In [ ]:
my_nuke_alarm(100, 96, 90)

normal
